from .Query import Query
from .Query1 import Query1
from .Query2 import Query2
from .Query3 import Query3
from .Query4 import Query4
from .Query5 import Query5
from .Query6 import Query6
from .Query7 import Query7
from .Query8 import Query8
