services:
  risingwave:
    image: risingwavelabs/risingwave:latest
    container_name: risingwave_nexmark
    ports:
      - "4566:4566"
      - "80:80"                              # Expose RisingWave port
    command: playground
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "4566"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

networks:
  default:
    external: true
    name: redpanda_network